klish
=====

Clone klish from https://src.libcode.org/klish

Original info
=============

* Homepage : http://klish.libcode.org.
* Additional documentation : http://klish.googlecode.com
* Repository : https://src.libcode.org/klish

Current changes
===============

* Indents are correct set indents for config read

TODO
====

+ [done] Correct use indents in config files generated by konfd (currently ignore all whitespaces) 
