- This script will provide specific details from the "show interface" command using an argument for the interface number and an argument for the artifact name.
- The interface argument should be in "Ethernet1/" format
- The human readable name for the artifact is the next argument e.g. MTU 
- Quotes are nesecary for artifacts with spaces in the name e.g. "IP Address"
