# nataas

NAT-as-a-service is my first NSO application.

More documentation will be coming soon!

# Supported Platforms
Any IOS devices

The majority of this repo is autogenerated by using
<NCS-DIR>/bin/ncs-setup --dest <local dir>


# Instructions
1. Clone this package (address-translation) into your NSO server's or project's packages directory.
2. In your NSO's command line (ncs_cli -C), perform a packages reload.
3. Now the package will appear in the modules menu as address-translation in your NSO's native UI.


# sample usage
The following commands can be used to interact with NCS in this directory:

```
ncs -c ./ncs.conf                         -- to start NCS as a daemon
ncs -c ./ncs.conf --foreground --verbose  -- start NCS in foregound
ncs --stop                                -- stop NCS
ncs_cli -u admin                          -- start a CLI into NCS
ncs-setup --eclipse-setup                 -- create eclipse dev files here
```
