Please see the full application usage document at https://haystacknetworks.com/cisco-apic-managed-object-browser

This code provides a browser in hierarchical tree format for the Cisco ACI APIC managed objects, this is an APIC stateless App, which means it is installed into and run from the APIC. This application was originally written as a standalone application which ran from a local machine. This has issues due to Cross-Origin Resource Sharing (CORS) and needed the browser to be run without web security and additionally for APIC's with using the locally generated SSL certificate, required the same browser session to open a connection to the APIC to accept the invalid certificate.

The application has been updated to run on the APIC in read only mode, the APIC provided this functionality at release 2.2(1n). Quoting from the Cisco ACI App Center Developer Guide - "The Cisco ACI App Center allows you to fully enable the capabilities of the APIC by writing applications running on the controller. Using the Cisco ACI App Center, customers, developers, and partners will be able to build applications to simplify, enhance, and visualize their use cases. These applications are hosted and shared at the Cisco ACI App Center and installed in the APIC." The original application is here: https://github.com/simonbirtles/aci-model-viewer

The updated application allows the user to use the application without the same issues as when running from a local machines or indeed any machine that is not the APIC, as the application runs on the APIC and uses single sign on (SSO) these issues are no longer prevalent. The application provides the ability to visually browse the APIC managed objects (MO) which is the configuration by objects and links between these objects - It’s a bit like visore but graphical and shows fault counts. Explore the context menus for more features like changing the root object and changing the filters set on objects, these filters are the same as the ones defined in the Cisco REST API guide.

The application code is in the src directory, in this directory is the packaged app (HaystackNetworks-ACIModelBrowser-1.0.aci) file is uploaded to the APIC via the Apps tab. This has the code in src packaged up. If you prefer to browse the source first and then package up yourself, use the all the files and directories in the src directory and follow the guide at https://developer.cisco.com/site/aci/docs/app-center/getting-started/index.gsp. You will need to download the "App Packager Utility" and install on Ubuntu or similar. The instructions to package an app can be found here: https://www.cisco.com/c/en/us/td/docs/switches/datacenter/aci/apic/sw/2-x/App_Center/developer_guide/b_Cisco_ACI_App_Center_Developer_Guide/b_Cisco_ACI_App_Center_Developer_Guide_chapter_0110.html

For example; when I create the package on Ubuntu, i use the following command where the directory the files are located from the src directory on Github is /haystacknetworks/aci-model-viewer-apic/: me@ubuntu:/haystacknetworks/cisco_aci_app_packager-1.0/packager#python aci_app_packager.py -f /haystacknetworks/aci-model-viewer-apic/

Notes:
1. Make sure you use the Github "clone or download" button, attempting to download the .aci file by using right click, save link as, causes the file to be unusable.
2. When the application is installed and enabled on the APIC, you may need to browse away from the Apps tab and back again before the applicartion open button will work - seems to be an APIC issue.
