# cisco-jabber-emoticons

Get the full set of emojis (2,300+) available on Cisco Jabber 

![jabber_emoji_demo](https://user-images.githubusercontent.com/13176059/31515311-b84c2e5e-af62-11e7-84db-6781e4751ec4.gif)


Move the `CustomEmoticons` folder into:
---------
For 32-bit operating systems:
```
 Program Files\Cisco Systems\Cisco Jabber\
```

For 64-bit operating systems:

```
Program Files(x86)\Cisco Systems\Cisco Jabber\
```

*make sure to restart the Cisco Jabber process to allow the changes to take effect*

## The Keyboard Shortcuts:


```
   ":1st_place_medal" 
   ":2nd_place_medal" 
   ":3rd_place_medal" 
   ":a_button_blood_type" 
   ":ab_button_blood_type" 
   ":admission_tickets" 
   ":aerial_tramway" 
   ":afghanistan" 
   ":airplane" 
   ":airplane_arrival" 
   ":airplane_departure" 
   ":alarm_clock" 
   ":albania" 
   ":alembic" 
   ":algeria" 
   ":alien" 
   ":alien_monster" 
   ":ambulance" 
   ":american_football" 
   ":american_samoa" 
   ":amphora" 
   ":anchor" 
   ":andorra" 
   ":anger_symbol" 
   ":angola" 
   ":angry_face" 
   ":angry_face_with_horns" 
   ":anguilla" 
   ":anguished_face" 
   ":ant" 
   ":antarctica" 
   ":antenna_bars" 
   ":antigua__barbuda" 
   ":anxious_face_with_sweat" 
   ":aquarius" 
   ":argentina" 
   ":aries" 
   ":armenia" 
   ":articulated_lorry" 
   ":artist_palette" 
   ":aruba" 
   ":ascension_island" 
   ":astonished_face" 
   ":atm_sign" 
   ":atom_symbol" 
   ":australia" 
   ":austria" 
   ":automobile" 
   ":avocado" 
   ":azerbaijan" 
   ":åland_islands" 
   ":b_button_blood_type" 
   ":baby" 
   ":baby_angel" 
   ":baby_angel_dark_skin_tone" 
   ":baby_angel_light_skin_tone" 
   ":baby_angel_medium_dark_skin_tone" 
   ":baby_angel_medium_light_skin_tone" 
   ":baby_angel_medium_skin_tone" 
   ":baby_bottle" 
   ":baby_chick" 
   ":baby_dark_skin_tone" 
   ":baby_light_skin_tone" 
   ":baby_medium_dark_skin_tone" 
   ":baby_medium_light_skin_tone" 
   ":baby_medium_skin_tone" 
   ":baby_symbol" 
   ":back_arrow" 
   ":backhand_index_pointing_down" 
   ":backhand_index_pointing_down_dark_skin_tone" pointing_down_dark_skin_tone"
   ":backhand_index_pointing_down_light_skin_tone" pointing_down_light_skin_tone"
   ":backhand_index_pointing_down_medium_dark_skin_tone" _index_pointing_down_medium_dark_skin_tone"
   ":backhand_index_pointing_down_medium_light_skin_tone" text="backhand_index_pointing_down_medium_light_skin_tone"
   ":backhand_index_pointing_down_medium_skin_tone" pointing_down_medium_skin_tone"
   ":backhand_index_pointing_left" 
   ":backhand_index_pointing_left_dark_skin_tone" pointing_left_dark_skin_tone"
   ":backhand_index_pointing_left_light_skin_tone" pointing_left_light_skin_tone"
   ":backhand_index_pointing_left_medium_dark_skin_tone" _index_pointing_left_medium_dark_skin_tone"
   ":backhand_index_pointing_left_medium_light_skin_tone" text="backhand_index_pointing_left_medium_light_skin_tone"
   ":backhand_index_pointing_left_medium_skin_tone" pointing_left_medium_skin_tone"
   ":backhand_index_pointing_right" 
   ":backhand_index_pointing_right_dark_skin_tone" pointing_right_dark_skin_tone"
   ":backhand_index_pointing_right_light_skin_tone" pointing_right_light_skin_tone"
   ":backhand_index_pointing_right_medium_dark_skin_tone" text="backhand_index_pointing_right_medium_dark_skin_tone"
   ":backhand_index_pointing_right_medium_light_skin_tone" text="backhand_index_pointing_right_medium_light_skin_tone"
   ":backhand_index_pointing_right_medium_skin_tone" pointing_right_medium_skin_tone"
   ":backhand_index_pointing_up" 
   ":backhand_index_pointing_up_dark_skin_tone" _dark_skin_tone"
   ":backhand_index_pointing_up_light_skin_tone" up_light_skin_tone"
   ":backhand_index_pointing_up_medium_dark_skin_tone" index_pointing_up_medium_dark_skin_tone"
   ":backhand_index_pointing_up_medium_light_skin_tone" index_pointing_up_medium_light_skin_tone"
   ":backhand_index_pointing_up_medium_skin_tone" pointing_up_medium_skin_tone"
   ":bacon" 
   ":badminton" 
   ":baggage_claim" 
   ":baguette_bread" 
   ":bahamas" 
   ":bahrain" 
   ":balance_scale" 
   ":balloon" 
   ":ballot_box_with_ballot" 
   ":ballot_box_with_check" 
   ":banana" 
   ":bangladesh" 
   ":bank" 
   ":bar_chart" 
   ":barbados" 
   ":barber_pole" 
   ":baseball" 
   ":basketball" 
   ":bat" 
   ":bathtub" 
   ":battery" 
   ":beach_with_umbrella" 
   ":beaming_face_with_smiling_eyes" 
   ":bear_face" 
   ":beating_heart" 
   ":bed" 
   ":beer_mug" 
   ":belarus" 
   ":belgium" 
   ":belize" 
   ":bell" 
   ":bell_with_slash" 
   ":bellhop_bell" 
   ":benin" 
   ":bento_box" 
   ":bermuda" 
   ":bhutan" 
   ":bicycle" 
   ":bikini" 
   ":biohazard" 
   ":bird" 
   ":birthday_cake" 
   ":black_circle" 
   ":black_flag" 
   ":black_heart" 
   ":black_large_square" 
   ":black_medium_small_square" 
   ":black_medium_square" 
   ":black_nib" 
   ":black_small_square" 
   ":black_square_button" 
   ":blond_haired_man" 
   ":blond_haired_man_dark_skin_tone" 
   ":blond_haired_man_light_skin_tone" 
   ":blond_haired_man_medium_dark_skin_tone" skin_tone"
   ":blond_haired_man_medium_light_skin_tone" _skin_tone"
   ":blond_haired_man_medium_skin_tone" 
   ":blond_haired_person" 
   ":blond_haired_person_dark_skin_tone" 
   ":blond_haired_person_light_skin_tone" skin_tone"
   ":blond_haired_person_medium_dark_skin_tone" medium_dark_skin_tone"
   ":blond_haired_person_medium_light_skin_tone" medium_light_skin_tone"
   ":blond_haired_person_medium_skin_tone" skin_tone"
   ":blond_haired_woman" 
   ":blond_haired_woman_dark_skin_tone" 
   ":blond_haired_woman_light_skin_tone" 
   ":blond_haired_woman_medium_dark_skin_tone" dark_skin_tone"
   ":blond_haired_woman_medium_light_skin_tone" _light_skin_tone"
   ":blond_haired_woman_medium_skin_tone" skin_tone"
   ":blossom" 
   ":blowfish" 
   ":blue_book" 
   ":blue_circle" 
   ":blue_heart" 
   ":boar" 
   ":bolivia" 
   ":bomb" 
   ":bookmark" 
   ":bookmark_tabs" 
   ":books" 
   ":bosnia__herzegovina" 
   ":botswana" 
   ":bottle_with_popping_cork" 
   ":bouquet" 
   ":bouvet_island" 
   ":bow_and_arrow" 
   ":bowling" 
   ":boxing_glove" 
   ":boy" 
   ":boy_dark_skin_tone" 
   ":boy_light_skin_tone" 
   ":boy_medium_dark_skin_tone" 
   ":boy_medium_light_skin_tone" 
   ":boy_medium_skin_tone" 
   ":brazil" 
   ":bread" 
   ":bride_with_veil" 
   ":bride_with_veil_dark_skin_tone" 
   ":bride_with_veil_light_skin_tone" 
   ":bride_with_veil_medium_dark_skin_tone" tone"
   ":bride_with_veil_medium_light_skin_tone" skin_tone"
   ":bride_with_veil_medium_skin_tone" 
   ":bridge_at_night" 
   ":briefcase" 
   ":bright_button" 
   ":british_indian_ocean_territory" 
   ":british_virgin_islands" 
   ":broken_heart" 
   ":brunei" 
   ":bug" 
   ":building_construction" 
   ":bulgaria" 
   ":bullet_train" 
   ":burkina_faso" 
   ":burrito" 
   ":burundi" 
   ":bus" 
   ":bus_stop" 
   ":bust_in_silhouette" 
   ":busts_in_silhouette" 
   ":butterfly" 
   ":cactus" 
   ":calendar" 
   ":call_me_hand" 
   ":call_me_hand_dark_skin_tone" 
   ":call_me_hand_light_skin_tone" 
   ":call_me_hand_medium_dark_skin_tone" 
   ":call_me_hand_medium_light_skin_tone" tone"
   ":call_me_hand_medium_skin_tone" 
   ":cambodia" 
   ":camel" 
   ":camera" 
   ":camera_with_flash" 
   ":cameroon" 
   ":camping" 
   ":canada" 
   ":canary_islands" 
   ":cancer" 
   ":candle" 
   ":candy" 
   ":canoe" 
   ":cape_verde" 
   ":capricorn" 
   ":card_file_box" 
   ":card_index" 
   ":card_index_dividers" 
   ":caribbean_netherlands" 
   ":carousel_horse" 
   ":carp_streamer" 
   ":carrot" 
   ":castle" 
   ":cat" 
   ":cat_face" 
   ":cat_face_with_tears_of_joy" 
   ":cat_face_with_wry_smile" 
   ":cayman_islands" 
   ":central_african_republic" 
   ":ceuta__melilla" 
   ":chad" 
   ":chains" 
   ":chart_decreasing" 
   ":chart_increasing" 
   ":chart_increasing_with_yen" 
   ":cheese_wedge" 
   ":chequered_flag" 
   ":cherries" 
   ":cherry_blossom" 
   ":chestnut" 
   ":chicken" 
   ":children_crossing" 
   ":chile" 
   ":china" 
   ":chipmunk" 
   ":chocolate_bar" 
   ":christmas_island" 
   ":christmas_tree" 
   ":church" 
   ":cigarette" 
   ":cinema" 
   ":circled_m" 
   ":circus_tent" 
   ":cityscape" 
   ":cityscape_at_dusk" 
   ":cl_button" 
   ":clamp" 
   ":clapper_board" 
   ":clapping_hands" 
   ":clapping_hands_dark_skin_tone" 
   ":clapping_hands_light_skin_tone" 
   ":clapping_hands_medium_dark_skin_tone" skin_tone"
   ":clapping_hands_medium_light_skin_tone" skin_tone"
   ":clapping_hands_medium_skin_tone" 
   ":classical_building" 
   ":clinking_beer_mugs" 
   ":clinking_glasses" 
   ":clipboard" 
   ":clipperton_island" 
   ":clockwise_vertical_arrows" 
   ":closed_book" 
   ":closed_mailbox_with_lowered_flag" 
   ":closed_mailbox_with_raised_flag" 
   ":closed_umbrella" 
   ":cloud" 
   ":cloud_with_lightning" 
   ":cloud_with_lightning_and_rain" 
   ":cloud_with_rain" 
   ":cloud_with_snow" 
   ":clown_face" 
   ":club_suit" 
   ":clutch_bag" 
   ":cocktail_glass" 
   ":cocos_keeling_islands" 
   ":coffin" 
   ":collision" 
   ":colombia" 
   ":comet" 
   ":comoros" 
   ":computer_disk" 
   ":computer_mouse" 
   ":confetti_ball" 
   ":confounded_face" 
   ":confused_face" 
   ":congo___brazzaville" 
   ":congo___kinshasa" 
   ":construction" 
   ":construction_worker" 
   ":construction_worker_dark_skin_tone" 
   ":construction_worker_light_skin_tone" tone"
   ":construction_worker_medium_dark_skin_tone" medium_dark_skin_tone"
   ":construction_worker_medium_light_skin_tone" medium_light_skin_tone"
   ":construction_worker_medium_skin_tone" tone"
   ":control_knobs" 
   ":convenience_store" 
   ":cook_islands" 
   ":cooked_rice" 
   ":cookie" 
   ":cooking" 
   ":cool_button" 
   ":copyright" 
   ":costa_rica" 
   ":couch_and_lamp" 
   ":counterclockwise_arrows_button" 
   ":couple_with_heart" 
   ":couple_with_heart_man_man" 
   ":couple_with_heart_woman_man" 
   ":couple_with_heart_woman_woman" 
   ":cow" 
   ":cow_face" 
   ":cowboy_hat_face" 
   ":côte_d’ivoire" 
   ":crab" 
   ":crayon" 
   ":credit_card" 
   ":crescent_moon" 
   ":cricket_game" 
   ":croatia" 
   ":crocodile" 
   ":croissant" 
   ":cross_mark" 
   ":cross_mark_button" 
   ":crossed_fingers" 
   ":crossed_fingers_dark_skin_tone" 
   ":crossed_fingers_light_skin_tone" 
   ":crossed_fingers_medium_dark_skin_tone" skin_tone"
   ":crossed_fingers_medium_light_skin_tone" skin_tone"
   ":crossed_fingers_medium_skin_tone" 
   ":crossed_flags" 
   ":crossed_swords" 
   ":crown" 
   ":crying_cat_face" 
   ":crying_face" 
   ":crystal_ball" 
   ":cuba" 
   ":cucumber" 
   ":curaçao" 
   ":curly_loop" 
   ":currency_exchange" 
   ":curry_rice" 
   ":custard" 
   ":customs" 
   ":cyclone" 
   ":cyprus" 
   ":czechia" 
   ":dagger" 
   ":dango" 
   ":dashing_away" 
   ":deciduous_tree" 
   ":deer" 
   ":delivery_truck" 
   ":denmark" 
   ":department_store" 
   ":derelict_house" 
   ":desert" 
   ":desert_island" 
   ":desktop_computer" 
   ":detective" 
   ":detective_dark_skin_tone" 
   ":detective_light_skin_tone" 
   ":detective_medium_dark_skin_tone" 
   ":detective_medium_light_skin_tone" 
   ":detective_medium_skin_tone" 
   ":diamond_suit" 
   ":diamond_with_a_dot" 
   ":diego_garcia" 
   ":dim_button" 
   ":direct_hit" 
   ":disappointed_face" 
   ":dizzy" 
   ":dizzy_face" 
   ":djibouti" 
   ":dog" 
   ":dog_face" 
   ":dollar_banknote" 
   ":dolphin" 
   ":dominica" 
   ":dominican_republic" 
   ":door" 
   ":dotted_six_pointed_star" 
   ":double_curly_loop" 
   ":double_exclamation_mark" 
   ":doughnut" 
   ":dove" 
   ":down_arrow" 
   ":down_button" 
   ":down_left_arrow" 
   ":down_right_arrow" 
   ":downcast_face_with_sweat" 
   ":dragon" 
   ":dragon_face" 
   ":dress" 
   ":drooling_face" 
   ":droplet" 
   ":drum" 
   ":duck" 
   ":dvd" 
   ":e_mail" 
   ":eagle" 
   ":ear" 
   ":ear_dark_skin_tone" 
   ":ear_light_skin_tone" 
   ":ear_medium_dark_skin_tone" 
   ":ear_medium_light_skin_tone" 
   ":ear_medium_skin_tone" 
   ":ear_of_corn" 
   ":ecuador" 
   ":egg" 
   ":eggplant" 
   ":egypt" 
   ":eight_o’clock" 
   ":eight_pointed_star" 
   ":eight_spoked_asterisk" 
   ":eight_thirty" 
   ":el_salvador" 
   ":electric_plug" 
   ":elephant" 
   ":eleven_o’clock" 
   ":eleven_thirty" 
   ":end_arrow" 
   ":envelope" 
   ":envelope_with_arrow" 
   ":equatorial_guinea" 
   ":eritrea" 
   ":estonia" 
   ":ethiopia" 
   ":euro_banknote" 
   ":european_union" 
   ":evergreen_tree" 
   ":ewe" 
   ":exclamation_mark" 
   ":exclamation_question_mark" 
   ":expressionless_face" 
   ":eye" 
   ":eye_in_speech_bubble" 
   ":eyes" 
   ":face_blowing_a_kiss" 
   ":face_savoring_food" 
   ":face_screaming_in_fear" 
   ":face_with_head_bandage" 
   ":face_with_medical_mask" 
   ":face_with_open_mouth" 
   ":face_with_rolling_eyes" 
   ":face_with_steam_from_nose" 
   ":face_with_tears_of_joy" 
   ":face_with_thermometer" 
   ":face_with_tongue" 
   ":face_without_mouth" 
   ":factory" 
   ":falkland_islands" 
   ":fallen_leaf" 
   ":family" 
   ":family_man_boy" 
   ":family_man_boy_boy" 
   ":family_man_girl" 
   ":family_man_girl_boy" 
   ":family_man_girl_girl" 
   ":family_man_man_boy" 
   ":family_man_man_boy_boy" 
   ":family_man_man_girl" 
   ":family_man_man_girl_boy" 
   ":family_man_man_girl_girl" 
   ":family_man_woman_boy" 
   ":family_man_woman_boy_boy" 
   ":family_man_woman_girl" 
   ":family_man_woman_girl_boy" 
   ":family_man_woman_girl_girl" 
   ":family_woman_boy" 
   ":family_woman_boy_boy" 
   ":family_woman_girl" 
   ":family_woman_girl_boy" 
   ":family_woman_girl_girl" 
   ":family_woman_woman_boy" 
   ":family_woman_woman_boy_boy" 
   ":family_woman_woman_girl" 
   ":family_woman_woman_girl_boy" 
   ":family_woman_woman_girl_girl" 
   ":faroe_islands" 
   ":fast_down_button" 
   ":fast_forward_button" 
   ":fast_reverse_button" 
   ":fast_up_button" 
   ":fax_machine" 
   ":fearful_face" 
   ":ferris_wheel" 
   ":ferry" 
   ":field_hockey" 
   ":fiji" 
   ":file_cabinet" 
   ":file_folder" 
   ":film_frames" 
   ":film_projector" 
   ":finland" 
   ":fire" 
   ":fire_engine" 
   ":fireworks" 
   ":first_quarter_moon" 
   ":first_quarter_moon_face" 
   ":fish" 
   ":fish_cake_with_swirl" 
   ":fishing_pole" 
   ":five_o’clock" 
   ":five_thirty" 
   ":flag_in_hole" 
   ":flashlight" 
   ":fleur_de_lis" 
   ":flexed_biceps" 
   ":flexed_biceps_dark_skin_tone" 
   ":flexed_biceps_light_skin_tone" 
   ":flexed_biceps_medium_dark_skin_tone" skin_tone"
   ":flexed_biceps_medium_light_skin_tone" skin_tone"
   ":flexed_biceps_medium_skin_tone" 
   ":floppy_disk" 
   ":flower_playing_cards" 
   ":flushed_face" 
   ":fog" 
   ":foggy" 
   ":folded_hands" 
   ":folded_hands_dark_skin_tone" 
   ":folded_hands_light_skin_tone" 
   ":folded_hands_medium_dark_skin_tone" 
   ":folded_hands_medium_light_skin_tone" skin_tone"
   ":folded_hands_medium_skin_tone" 
   ":footprints" 
   ":fork_and_knife" 
   ":fork_and_knife_with_plate" 
   ":fountain" 
   ":fountain_pen" 
   ":four_leaf_clover" 
   ":four_o’clock" 
   ":four_thirty" 
   ":fox_face" 
   ":framed_picture" 
   ":france" 
   ":free_button" 
   ":french_fries" 
   ":french_guiana" 
   ":french_polynesia" 
   ":french_southern_territories" 
   ":fried_shrimp" 
   ":frog_face" 
   ":front_facing_baby_chick" 
   ":frowning_face" 
   ":frowning_face_with_open_mouth" 
   ":fuel_pump" 
   ":full_moon" 
   ":full_moon_face" 
   ":funeral_urn" 
   ":gabon" 
   ":gambia" 
   ":game_die" 
   ":gear" 
   ":gem_stone" 
   ":gemini" 
   ":georgia" 
   ":germany" 
   ":ghana" 
   ":ghost" 
   ":gibraltar" 
   ":girl" 
   ":girl_dark_skin_tone" 
   ":girl_light_skin_tone" 
   ":girl_medium_dark_skin_tone" 
   ":girl_medium_light_skin_tone" 
   ":girl_medium_skin_tone" 
   ":glass_of_milk" 
   ":glasses" 
   ":globe_showing_americas" 
   ":globe_showing_asia_australia" 
   ":globe_showing_europe_africa" 
   ":globe_with_meridians" 
   ":glowing_star" 
   ":goal_net" 
   ":goat" 
   ":goblin" 
   ":gorilla" 
   ":graduation_cap" 
   ":grapes" 
   ":greece" 
   ":green_apple" 
   ":green_book" 
   ":green_heart" 
   ":green_salad" 
   ":greenland" 
   ":grenada" 
   ":grimacing_face" 
   ":grinning_cat_face" 
   ":grinning_cat_face_with_smiling_eyes" smiling_eyes"
   ":grinning_face" 
   ":grinning_face_with_big_eyes" 
   ":grinning_face_with_smiling_eyes" 
   ":grinning_face_with_sweat" 
   ":grinning_squinting_face" 
   ":growing_heart" 
   ":guadeloupe" 
   ":guam" 
   ":guard" 
   ":guard_dark_skin_tone" 
   ":guard_light_skin_tone" 
   ":guard_medium_dark_skin_tone" 
   ":guard_medium_light_skin_tone" 
   ":guard_medium_skin_tone" 
   ":guatemala" 
   ":guernsey" 
   ":guinea" 
   ":guinea_bissau" 
   ":guitar" 
   ":guyana" 
   ":haiti" 
   ":hamburger" 
   ":hammer" 
   ":hammer_and_pick" 
   ":hammer_and_wrench" 
   ":hamster_face" 
   ":hand_with_fingers_splayed" 
   ":hand_with_fingers_splayed_dark_skin_tone" dark_skin_tone"
   ":hand_with_fingers_splayed_light_skin_tone" _light_skin_tone"
   ":hand_with_fingers_splayed_medium_dark_skin_tone" fingers_splayed_medium_dark_skin_tone"
   ":hand_with_fingers_splayed_medium_light_skin_tone" fingers_splayed_medium_light_skin_tone"
   ":hand_with_fingers_splayed_medium_skin_tone" splayed_medium_skin_tone"
   ":handbag" 
   ":handshake" 
   ":hatching_chick" 
   ":headphone" 
   ":hear_no_evil_monkey" 
   ":heard__mcdonald_islands" 
   ":heart_decoration" 
   ":heart_suit" 
   ":heart_with_arrow" 
   ":heart_with_ribbon" 
   ":heavy_check_mark" 
   ":heavy_division_sign" 
   ":heavy_dollar_sign" 
   ":heavy_heart_exclamation" 
   ":heavy_large_circle" 
   ":heavy_minus_sign" 
   ":heavy_multiplication_x" 
   ":heavy_plus_sign" 
   ":helicopter" 
   ":herb" 
   ":hibiscus" 
   ":high_heeled_shoe" 
   ":high_speed_train" 
   ":high_voltage" 
   ":hole" 
   ":honduras" 
   ":honey_pot" 
   ":honeybee" 
   ":hong_kong_sar_china" 
   ":horizontal_traffic_light" 
   ":horse" 
   ":horse_face" 
   ":horse_racing" 
   ":horse_racing_dark_skin_tone" 
   ":horse_racing_light_skin_tone" 
   ":horse_racing_medium_dark_skin_tone" 
   ":horse_racing_medium_light_skin_tone" skin_tone"
   ":horse_racing_medium_skin_tone" 
   ":hospital" 
   ":hot_beverage" 
   ":hot_dog" 
   ":hot_pepper" 
   ":hot_springs" 
   ":hotel" 
   ":hourglass_done" 
   ":hourglass_not_done" 
   ":house" 
   ":house_with_garden" 
   ":houses" 
   ":hugging_face" 
   ":hundred_points" 
   ":hungary" 
   ":hushed_face" 
   ":ice_cream" 
   ":ice_hockey" 
   ":ice_skate" 
   ":iceland" 
   ":id_button" 
   ":inbox_tray" 
   ":incoming_envelope" 
   ":index_pointing_up" 
   ":index_pointing_up_dark_skin_tone" 
   ":index_pointing_up_light_skin_tone" 
   ":index_pointing_up_medium_dark_skin_tone" _skin_tone"
   ":index_pointing_up_medium_light_skin_tone" light_skin_tone"
   ":index_pointing_up_medium_skin_tone" 
   ":india" 
   ":indonesia" 
   ":information" 
   ":input_latin_letters" 
   ":input_latin_lowercase" 
   ":input_latin_uppercase" 
   ":input_numbers" 
   ":input_symbols" 
   ":iran" 
   ":iraq" 
   ":ireland" 
   ":isle_of_man" 
   ":israel" 
   ":italy" 
   ":jack_o_lantern" 
   ":jamaica" 
   ":japan" 
   ":japanese_castle" 
   ":japanese_dolls" 
   ":japanese_post_office" 
   ":japanese_symbol_for_beginner" 
   ":japanese_“acceptable”_button" 
   ":japanese_“application”_button" 
   ":japanese_“bargain”_button" 
   ":japanese_“congratulations”_button" 
   ":japanese_“discount”_button" 
   ":japanese_“free_of_charge”_button" 
   ":japanese_“here”_button" 
   ":japanese_“monthly_amount”_button" 
   ":japanese_“no_vacancy”_button" 
   ":japanese_“not_free_of_charge”_button" charge”_button"
   ":japanese_“open_for_business”_button" button"
   ":japanese_“passing_grade”_button" 
   ":japanese_“prohibited”_button" 
   ":japanese_“reserved”_button" 
   ":japanese_“secret”_button" 
   ":japanese_“service_charge”_button" 
   ":japanese_“vacancy”_button" 
   ":jeans" 
   ":jersey" 
   ":joker" 
   ":jordan" 
   ":joystick" 
   ":kaaba" 
   ":kazakhstan" 
   ":kenya" 
   ":key" 
   ":keyboard" 
   ":keycap_#" 
   ":keycap_*" 
   ":keycap_0" 
   ":keycap_1" 
   ":keycap_10" 
   ":keycap_2" 
   ":keycap_3" 
   ":keycap_4" 
   ":keycap_5" 
   ":keycap_6" 
   ":keycap_7" 
   ":keycap_8" 
   ":keycap_9" 
   ":kick_scooter" 
   ":kimono" 
   ":kiribati" 
   ":kiss" 
   ":kiss_man_man" 
   ":kiss_mark" 
   ":kiss_woman_man" 
   ":kiss_woman_woman" 
   ":kissing_cat_face" 
   ":kissing_face" 
   ":kissing_face_with_closed_eyes" 
   ":kissing_face_with_smiling_eyes" 
   ":kitchen_knife" 
   ":kiwi_fruit" 
   ":koala" 
   ":kosovo" 
   ":kuwait" 
   ":kyrgyzstan" 
   ":label" 
   ":lady_beetle" 
   ":laos" 
   ":laptop_computer" 
   ":large_blue_diamond" 
   ":large_orange_diamond" 
   ":last_quarter_moon" 
   ":last_quarter_moon_face" 
   ":last_track_button" 
   ":latin_cross" 
   ":latvia" 
   ":leaf_fluttering_in_wind" 
   ":lebanon" 
   ":ledger" 
   ":left_arrow" 
   ":left_arrow_curving_right" 
   ":left_facing_fist" 
   ":left_facing_fist_dark_skin_tone" 
   ":left_facing_fist_light_skin_tone" 
   ":left_facing_fist_medium_dark_skin_tone" skin_tone"
   ":left_facing_fist_medium_light_skin_tone" _skin_tone"
   ":left_facing_fist_medium_skin_tone" 
   ":left_luggage" 
   ":left_right_arrow" 
   ":left_speech_bubble" 
   ":lemon" 
   ":leo" 
   ":leopard" 
   ":lesotho" 
   ":level_slider" 
   ":liberia" 
   ":libra" 
   ":libya" 
   ":liechtenstein" 
   ":light_bulb" 
   ":light_rail" 
   ":link" 
   ":linked_paperclips" 
   ":lion_face" 
   ":lipstick" 
   ":lithuania" 
   ":litter_in_bin_sign" 
   ":lizard" 
   ":locked" 
   ":locked_with_key" 
   ":locked_with_pen" 
   ":locomotive" 
   ":lollipop" 
   ":loudly_crying_face" 
   ":loudspeaker" 
   ":love_hotel" 
   ":love_letter" 
   ":luxembourg" 
   ":lying_face" 
   ":macau_sar_china" 
   ":macedonia" 
   ":madagascar" 
   ":magnifying_glass_tilted_left" 
   ":magnifying_glass_tilted_right" 
   ":mahjong_red_dragon" 
   ":malawi" 
   ":malaysia" 
   ":maldives" 
   ":mali" 
   ":malta" 
   ":man" 
   ":man_and_woman_holding_hands" 
   ":man_artist" 
   ":man_artist_dark_skin_tone" 
   ":man_artist_light_skin_tone" 
   ":man_artist_medium_dark_skin_tone" 
   ":man_artist_medium_light_skin_tone" 
   ":man_artist_medium_skin_tone" 
   ":man_astronaut" 
   ":man_astronaut_dark_skin_tone" 
   ":man_astronaut_light_skin_tone" 
   ":man_astronaut_medium_dark_skin_tone" skin_tone"
   ":man_astronaut_medium_light_skin_tone" skin_tone"
   ":man_astronaut_medium_skin_tone" 
   ":man_biking" 
   ":man_biking_dark_skin_tone" 
   ":man_biking_light_skin_tone" 
   ":man_biking_medium_dark_skin_tone" 
   ":man_biking_medium_light_skin_tone" 
   ":man_biking_medium_skin_tone" 
   ":man_bouncing_ball" 
   ":man_bouncing_ball_dark_skin_tone" 
   ":man_bouncing_ball_light_skin_tone" 
   ":man_bouncing_ball_medium_dark_skin_tone" _skin_tone"
   ":man_bouncing_ball_medium_light_skin_tone" light_skin_tone"
   ":man_bouncing_ball_medium_skin_tone" 
   ":man_bowing" 
   ":man_bowing_dark_skin_tone" 
   ":man_bowing_light_skin_tone" 
   ":man_bowing_medium_dark_skin_tone" 
   ":man_bowing_medium_light_skin_tone" 
   ":man_bowing_medium_skin_tone" 
   ":man_cartwheeling" 
   ":man_cartwheeling_dark_skin_tone" 
   ":man_cartwheeling_light_skin_tone" 
   ":man_cartwheeling_medium_dark_skin_tone" skin_tone"
   ":man_cartwheeling_medium_light_skin_tone" _skin_tone"
   ":man_cartwheeling_medium_skin_tone" 
   ":man_construction_worker" 
   ":man_construction_worker_dark_skin_tone" skin_tone"
   ":man_construction_worker_light_skin_tone" _skin_tone"
   ":man_construction_worker_medium_dark_skin_tone" worker_medium_dark_skin_tone"
   ":man_construction_worker_medium_light_skin_tone" construction_worker_medium_light_skin_tone"
   ":man_construction_worker_medium_skin_tone" medium_skin_tone"
   ":man_cook" 
   ":man_cook_dark_skin_tone" 
   ":man_cook_light_skin_tone" 
   ":man_cook_medium_dark_skin_tone" 
   ":man_cook_medium_light_skin_tone" 
   ":man_cook_medium_skin_tone" 
   ":man_dancing" 
   ":man_dancing_dark_skin_tone" 
   ":man_dancing_light_skin_tone" 
   ":man_dancing_medium_dark_skin_tone" 
   ":man_dancing_medium_light_skin_tone" 
   ":man_dancing_medium_skin_tone" 
   ":man_dark_skin_tone" 
   ":man_detective" 
   ":man_detective_dark_skin_tone" 
   ":man_detective_light_skin_tone" 
   ":man_detective_medium_dark_skin_tone" skin_tone"
   ":man_detective_medium_light_skin_tone" skin_tone"
   ":man_detective_medium_skin_tone" 
   ":man_facepalming" 
   ":man_facepalming_dark_skin_tone" 
   ":man_facepalming_light_skin_tone" 
   ":man_facepalming_medium_dark_skin_tone" skin_tone"
   ":man_facepalming_medium_light_skin_tone" skin_tone"
   ":man_facepalming_medium_skin_tone" 
   ":man_factory_worker" 
   ":man_factory_worker_dark_skin_tone" 
   ":man_factory_worker_light_skin_tone" 
   ":man_factory_worker_medium_dark_skin_tone" dark_skin_tone"
   ":man_factory_worker_medium_light_skin_tone" _light_skin_tone"
   ":man_factory_worker_medium_skin_tone" skin_tone"
   ":man_farmer" 
   ":man_farmer_dark_skin_tone" 
   ":man_farmer_light_skin_tone" 
   ":man_farmer_medium_dark_skin_tone" 
   ":man_farmer_medium_light_skin_tone" 
   ":man_farmer_medium_skin_tone" 
   ":man_firefighter" 
   ":man_firefighter_dark_skin_tone" 
   ":man_firefighter_light_skin_tone" 
   ":man_firefighter_medium_dark_skin_tone" skin_tone"
   ":man_firefighter_medium_light_skin_tone" skin_tone"
   ":man_firefighter_medium_skin_tone" 
   ":man_frowning" 
   ":man_frowning_dark_skin_tone" 
   ":man_frowning_light_skin_tone" 
   ":man_frowning_medium_dark_skin_tone" 
   ":man_frowning_medium_light_skin_tone" skin_tone"
   ":man_frowning_medium_skin_tone" 
   ":man_gesturing_no" 
   ":man_gesturing_no_dark_skin_tone" 
   ":man_gesturing_no_light_skin_tone" 
   ":man_gesturing_no_medium_dark_skin_tone" skin_tone"
   ":man_gesturing_no_medium_light_skin_tone" _skin_tone"
   ":man_gesturing_no_medium_skin_tone" 
   ":man_gesturing_ok" 
   ":man_gesturing_ok_dark_skin_tone" 
   ":man_gesturing_ok_light_skin_tone" 
   ":man_gesturing_ok_medium_dark_skin_tone" skin_tone"
   ":man_gesturing_ok_medium_light_skin_tone" _skin_tone"
   ":man_gesturing_ok_medium_skin_tone" 
   ":man_getting_haircut" 
   ":man_getting_haircut_dark_skin_tone" 
   ":man_getting_haircut_light_skin_tone" skin_tone"
   ":man_getting_haircut_medium_dark_skin_tone" medium_dark_skin_tone"
   ":man_getting_haircut_medium_light_skin_tone" medium_light_skin_tone"
   ":man_getting_haircut_medium_skin_tone" skin_tone"
   ":man_getting_massage" 
   ":man_getting_massage_dark_skin_tone" 
   ":man_getting_massage_light_skin_tone" skin_tone"
   ":man_getting_massage_medium_dark_skin_tone" medium_dark_skin_tone"
   ":man_getting_massage_medium_light_skin_tone" medium_light_skin_tone"
   ":man_getting_massage_medium_skin_tone" skin_tone"
   ":man_golfing" 
   ":man_golfing_dark_skin_tone" 
   ":man_golfing_light_skin_tone" 
   ":man_golfing_medium_dark_skin_tone" 
   ":man_golfing_medium_light_skin_tone" 
   ":man_golfing_medium_skin_tone" 
   ":man_guard" 
   ":man_guard_dark_skin_tone" 
   ":man_guard_light_skin_tone" 
   ":man_guard_medium_dark_skin_tone" 
   ":man_guard_medium_light_skin_tone" 
   ":man_guard_medium_skin_tone" 
   ":man_health_worker" 
   ":man_health_worker_dark_skin_tone" 
   ":man_health_worker_light_skin_tone" 
   ":man_health_worker_medium_dark_skin_tone" _skin_tone"
   ":man_health_worker_medium_light_skin_tone" light_skin_tone"
   ":man_health_worker_medium_skin_tone" 
   ":man_in_suit_levitating" 
   ":man_in_suit_levitating_dark_skin_tone" tone"
   ":man_in_suit_levitating_light_skin_tone" skin_tone"
   ":man_in_suit_levitating_medium_dark_skin_tone" levitating_medium_dark_skin_tone"
   ":man_in_suit_levitating_medium_light_skin_tone" levitating_medium_light_skin_tone"
   ":man_in_suit_levitating_medium_skin_tone" medium_skin_tone"
   ":man_in_tuxedo" 
   ":man_in_tuxedo_dark_skin_tone" 
   ":man_in_tuxedo_light_skin_tone" 
   ":man_in_tuxedo_medium_dark_skin_tone" tone"
   ":man_in_tuxedo_medium_light_skin_tone" tone"
   ":man_in_tuxedo_medium_skin_tone" 
   ":man_judge" 
   ":man_judge_dark_skin_tone" 
   ":man_judge_light_skin_tone" 
   ":man_judge_medium_dark_skin_tone" 
   ":man_judge_medium_light_skin_tone" 
   ":man_judge_medium_skin_tone" 
   ":man_juggling" 
   ":man_juggling_dark_skin_tone" 
   ":man_juggling_light_skin_tone" 
   ":man_juggling_medium_dark_skin_tone" 
   ":man_juggling_medium_light_skin_tone" skin_tone"
   ":man_juggling_medium_skin_tone" 
   ":man_lifting_weights" 
   ":man_lifting_weights_dark_skin_tone" 
   ":man_lifting_weights_light_skin_tone" skin_tone"
   ":man_lifting_weights_medium_dark_skin_tone" medium_dark_skin_tone"
   ":man_lifting_weights_medium_light_skin_tone" medium_light_skin_tone"
   ":man_lifting_weights_medium_skin_tone" skin_tone"
   ":man_light_skin_tone" 
   ":man_mechanic" 
   ":man_mechanic_dark_skin_tone" 
   ":man_mechanic_light_skin_tone" 
   ":man_mechanic_medium_dark_skin_tone" 
   ":man_mechanic_medium_light_skin_tone" skin_tone"
   ":man_mechanic_medium_skin_tone" 
   ":man_medium_dark_skin_tone" 
   ":man_medium_light_skin_tone" 
   ":man_medium_skin_tone" 
   ":man_mountain_biking" 
   ":man_mountain_biking_dark_skin_tone" 
   ":man_mountain_biking_light_skin_tone" skin_tone"
   ":man_mountain_biking_medium_dark_skin_tone" medium_dark_skin_tone"
   ":man_mountain_biking_medium_light_skin_tone" medium_light_skin_tone"
   ":man_mountain_biking_medium_skin_tone" skin_tone"
   ":man_office_worker" 
   ":man_office_worker_dark_skin_tone" 
   ":man_office_worker_light_skin_tone" 
   ":man_office_worker_medium_dark_skin_tone" dark_skin_tone"
   ":man_office_worker_medium_light_skin_tone" light_skin_tone"
   ":man_office_worker_medium_skin_tone" 
   ":man_pilot" 
   ":man_pilot_dark_skin_tone" 
   ":man_pilot_light_skin_tone" 
   ":man_pilot_medium_dark_skin_tone" 
   ":man_pilot_medium_light_skin_tone" 
   ":man_pilot_medium_skin_tone" 
   ":man_playing_handball" 
   ":man_playing_handball_dark_skin_tone" skin_tone"
   ":man_playing_handball_light_skin_tone" skin_tone"
   ":man_playing_handball_medium_dark_skin_tone" medium_dark_skin_tone"
   ":man_playing_handball_medium_light_skin_tone" _medium_light_skin_tone"
   ":man_playing_handball_medium_skin_tone" skin_tone"
   ":man_playing_water_polo" 
   ":man_playing_water_polo_dark_skin_tone" _tone"
   ":man_playing_water_polo_light_skin_tone" skin_tone"
   ":man_playing_water_polo_medium_dark_skin_tone" polo_medium_dark_skin_tone"
   ":man_playing_water_polo_medium_light_skin_tone" water_polo_medium_light_skin_tone"
   ":man_playing_water_polo_medium_skin_tone" medium_skin_tone"
   ":man_police_officer" 
   ":man_police_officer_dark_skin_tone" 
   ":man_police_officer_light_skin_tone" 
   ":man_police_officer_medium_dark_skin_tone" dark_skin_tone"
   ":man_police_officer_medium_light_skin_tone" medium_light_skin_tone"
   ":man_police_officer_medium_skin_tone" skin_tone"
   ":man_pouting" 
   ":man_pouting_dark_skin_tone" 
   ":man_pouting_light_skin_tone" 
   ":man_pouting_medium_dark_skin_tone" 
   ":man_pouting_medium_light_skin_tone" 
   ":man_pouting_medium_skin_tone" 
   ":man_raising_hand" 
   ":man_raising_hand_dark_skin_tone" 
   ":man_raising_hand_light_skin_tone" 
   ":man_raising_hand_medium_dark_skin_tone" skin_tone"
   ":man_raising_hand_medium_light_skin_tone" light_skin_tone"
   ":man_raising_hand_medium_skin_tone" 
   ":man_rowing_boat" 
   ":man_rowing_boat_dark_skin_tone" 
   ":man_rowing_boat_light_skin_tone" 
   ":man_rowing_boat_medium_dark_skin_tone" _tone"
   ":man_rowing_boat_medium_light_skin_tone" skin_tone"
   ":man_rowing_boat_medium_skin_tone" 
   ":man_running" 
   ":man_running_dark_skin_tone" 
   ":man_running_light_skin_tone" 
   ":man_running_medium_dark_skin_tone" 
   ":man_running_medium_light_skin_tone" 
   ":man_running_medium_skin_tone" 
   ":man_scientist" 
   ":man_scientist_dark_skin_tone" 
   ":man_scientist_light_skin_tone" 
   ":man_scientist_medium_dark_skin_tone" skin_tone"
   ":man_scientist_medium_light_skin_tone" skin_tone"
   ":man_scientist_medium_skin_tone" 
   ":man_shrugging" 
   ":man_shrugging_dark_skin_tone" 
   ":man_shrugging_light_skin_tone" 
   ":man_shrugging_medium_dark_skin_tone" skin_tone"
   ":man_shrugging_medium_light_skin_tone" skin_tone"
   ":man_shrugging_medium_skin_tone" 
   ":man_singer" 
   ":man_singer_dark_skin_tone" 
   ":man_singer_light_skin_tone" 
   ":man_singer_medium_dark_skin_tone" 
   ":man_singer_medium_light_skin_tone" 
   ":man_singer_medium_skin_tone" 
   ":man_student" 
   ":man_student_dark_skin_tone" 
   ":man_student_light_skin_tone" 
   ":man_student_medium_dark_skin_tone" 
   ":man_student_medium_light_skin_tone" 
   ":man_student_medium_skin_tone" 
   ":man_surfing" 
   ":man_surfing_dark_skin_tone" 
   ":man_surfing_light_skin_tone" 
   ":man_surfing_medium_dark_skin_tone" 
   ":man_surfing_medium_light_skin_tone" 
   ":man_surfing_medium_skin_tone" 
   ":man_swimming" 
   ":man_swimming_dark_skin_tone" 
   ":man_swimming_light_skin_tone" 
   ":man_swimming_medium_dark_skin_tone" 
   ":man_swimming_medium_light_skin_tone" skin_tone"
   ":man_swimming_medium_skin_tone" 
   ":man_teacher" 
   ":man_teacher_dark_skin_tone" 
   ":man_teacher_light_skin_tone" 
   ":man_teacher_medium_dark_skin_tone" 
   ":man_teacher_medium_light_skin_tone" 
   ":man_teacher_medium_skin_tone" 
   ":man_technologist" 
   ":man_technologist_dark_skin_tone" 
   ":man_technologist_light_skin_tone" 
   ":man_technologist_medium_dark_skin_tone" skin_tone"
   ":man_technologist_medium_light_skin_tone" light_skin_tone"
   ":man_technologist_medium_skin_tone" 
   ":man_tipping_hand" 
   ":man_tipping_hand_dark_skin_tone" 
   ":man_tipping_hand_light_skin_tone" 
   ":man_tipping_hand_medium_dark_skin_tone" skin_tone"
   ":man_tipping_hand_medium_light_skin_tone" light_skin_tone"
   ":man_tipping_hand_medium_skin_tone" 
   ":man_walking" 
   ":man_walking_dark_skin_tone" 
   ":man_walking_light_skin_tone" 
   ":man_walking_medium_dark_skin_tone" 
   ":man_walking_medium_light_skin_tone" 
   ":man_walking_medium_skin_tone" 
   ":man_wearing_turban" 
   ":man_wearing_turban_dark_skin_tone" 
   ":man_wearing_turban_light_skin_tone" 
   ":man_wearing_turban_medium_dark_skin_tone" dark_skin_tone"
   ":man_wearing_turban_medium_light_skin_tone" medium_light_skin_tone"
   ":man_wearing_turban_medium_skin_tone" skin_tone"
   ":man_with_chinese_cap" 
   ":man_with_chinese_cap_dark_skin_tone" tone"
   ":man_with_chinese_cap_light_skin_tone" tone"
   ":man_with_chinese_cap_medium_dark_skin_tone" medium_dark_skin_tone"
   ":man_with_chinese_cap_medium_light_skin_tone" _medium_light_skin_tone"
   ":man_with_chinese_cap_medium_skin_tone" _tone"
   ":mantelpiece_clock" 
   ":man’s_shoe" 
   ":map_of_japan" 
   ":maple_leaf" 
   ":marshall_islands" 
   ":martial_arts_uniform" 
   ":martinique" 
   ":mauritania" 
   ":mauritius" 
   ":mayotte" 
   ":meat_on_bone" 
   ":medical_symbol" 
   ":megaphone" 
   ":melon" 
   ":memo" 
   ":men_with_bunny_ears" 
   ":men_wrestling" 
   ":menorah" 
   ":men’s_room" 
   ":metro" 
   ":mexico" 
   ":micronesia" 
   ":microphone" 
   ":microscope" 
   ":middle_finger" 
   ":middle_finger_dark_skin_tone" 
   ":middle_finger_light_skin_tone" 
   ":middle_finger_medium_dark_skin_tone" skin_tone"
   ":middle_finger_medium_light_skin_tone" skin_tone"
   ":middle_finger_medium_skin_tone" 
   ":military_medal" 
   ":milky_way" 
   ":minibus" 
   ":moai" 
   ":mobile_phone" 
   ":mobile_phone_off" 
   ":mobile_phone_with_arrow" 
   ":moldova" 
   ":monaco" 
   ":money_bag" 
   ":money_mouth_face" 
   ":money_with_wings" 
   ":mongolia" 
   ":monkey" 
   ":monkey_face" 
   ":monorail" 
   ":montenegro" 
   ":montserrat" 
   ":moon_viewing_ceremony" 
   ":morocco" 
   ":mosque" 
   ":motor_boat" 
   ":motor_scooter" 
   ":motorcycle" 
   ":motorway" 
   ":mount_fuji" 
   ":mountain" 
   ":mountain_cableway" 
   ":mountain_railway" 
   ":mouse" 
   ":mouse_face" 
   ":mouth" 
   ":movie_camera" 
   ":mozambique" 
   ":mrs_claus" 
   ":mrs_claus_dark_skin_tone" 
   ":mrs_claus_light_skin_tone" 
   ":mrs_claus_medium_dark_skin_tone" 
   ":mrs_claus_medium_light_skin_tone" 
   ":mrs_claus_medium_skin_tone" 
   ":mushroom" 
   ":musical_keyboard" 
   ":musical_note" 
   ":musical_notes" 
   ":musical_score" 
   ":muted_speaker" 
   ":myanmar_burma" 
   ":nail_polish" 
   ":nail_polish_dark_skin_tone" 
   ":nail_polish_light_skin_tone" 
   ":nail_polish_medium_dark_skin_tone" 
   ":nail_polish_medium_light_skin_tone" 
   ":nail_polish_medium_skin_tone" 
   ":name_badge" 
   ":namibia" 
   ":national_park" 
   ":nauru" 
   ":nauseated_face" 
   ":necktie" 
   ":nepal" 
   ":nerd_face" 
   ":netherlands" 
   ":neutral_face" 
   ":new_button" 
   ":new_caledonia" 
   ":new_moon" 
   ":new_moon_face" 
   ":new_zealand" 
   ":newspaper" 
   ":next_track_button" 
   ":ng_button" 
   ":nicaragua" 
   ":niger" 
   ":nigeria" 
   ":night_with_stars" 
   ":nine_o’clock" 
   ":nine_thirty" 
   ":niue" 
   ":no_bicycles" 
   ":no_entry" 
   ":no_littering" 
   ":no_mobile_phones" 
   ":no_one_under_eighteen" 
   ":no_pedestrians" 
   ":no_smoking" 
   ":non_potable_water" 
   ":norfolk_island" 
   ":north_korea" 
   ":northern_mariana_islands" 
   ":norway" 
   ":nose" 
   ":nose_dark_skin_tone" 
   ":nose_light_skin_tone" 
   ":nose_medium_dark_skin_tone" 
   ":nose_medium_light_skin_tone" 
   ":nose_medium_skin_tone" 
   ":notebook" 
   ":notebook_with_decorative_cover" 
   ":nut_and_bolt" 
   ":o_button_blood_type" 
   ":octopus" 
   ":oden" 
   ":office_building" 
   ":ogre" 
   ":oil_drum" 
   ":ok_button" 
   ":ok_hand" 
   ":ok_hand_dark_skin_tone" 
   ":ok_hand_light_skin_tone" 
   ":ok_hand_medium_dark_skin_tone" 
   ":ok_hand_medium_light_skin_tone" 
   ":ok_hand_medium_skin_tone" 
   ":old_key" 
   ":old_man" 
   ":old_man_dark_skin_tone" 
   ":old_man_light_skin_tone" 
   ":old_man_medium_dark_skin_tone" 
   ":old_man_medium_light_skin_tone" 
   ":old_man_medium_skin_tone" 
   ":old_woman" 
   ":old_woman_dark_skin_tone" 
   ":old_woman_light_skin_tone" 
   ":old_woman_medium_dark_skin_tone" 
   ":old_woman_medium_light_skin_tone" 
   ":old_woman_medium_skin_tone" 
   ":om" 
   ":oman" 
   ":on_arrow" 
   ":oncoming_automobile" 
   ":oncoming_bus" 
   ":oncoming_fist" 
   ":oncoming_fist_dark_skin_tone" 
   ":oncoming_fist_light_skin_tone" 
   ":oncoming_fist_medium_dark_skin_tone" skin_tone"
   ":oncoming_fist_medium_light_skin_tone" skin_tone"
   ":oncoming_fist_medium_skin_tone" 
   ":oncoming_police_car" 
   ":oncoming_taxi" 
   ":one_o’clock" 
   ":one_thirty" 
   ":open_book" 
   ":open_file_folder" 
   ":open_hands" 
   ":open_hands_dark_skin_tone" 
   ":open_hands_light_skin_tone" 
   ":open_hands_medium_dark_skin_tone" 
   ":open_hands_medium_light_skin_tone" 
   ":open_hands_medium_skin_tone" 
   ":open_mailbox_with_lowered_flag" 
   ":open_mailbox_with_raised_flag" 
   ":ophiuchus" 
   ":optical_disk" 
   ":orange_book" 
   ":orthodox_cross" 
   ":outbox_tray" 
   ":owl" 
   ":ox" 
   ":p_button" 
   ":package" 
   ":page_facing_up" 
   ":page_with_curl" 
   ":pager" 
   ":paintbrush" 
   ":pakistan" 
   ":palau" 
   ":palestinian_territories" 
   ":palm_tree" 
   ":panama" 
   ":pancakes" 
   ":panda_face" 
   ":paperclip" 
   ":papua_new_guinea" 
   ":paraguay" 
   ":part_alternation_mark" 
   ":party_popper" 
   ":passenger_ship" 
   ":passport_control" 
   ":pause_button" 
   ":paw_prints" 
   ":peace_symbol" 
   ":peach" 
   ":peanuts" 
   ":pear" 
   ":pen" 
   ":pencil" 
   ":penguin" 
   ":pensive_face" 
   ":people_with_bunny_ears" 
   ":people_wrestling" 
   ":performing_arts" 
   ":persevering_face" 
   ":person_biking" 
   ":person_biking_dark_skin_tone" 
   ":person_biking_light_skin_tone" 
   ":person_biking_medium_dark_skin_tone" skin_tone"
   ":person_biking_medium_light_skin_tone" skin_tone"
   ":person_biking_medium_skin_tone" 
   ":person_bouncing_ball" 
   ":person_bouncing_ball_dark_skin_tone" skin_tone"
   ":person_bouncing_ball_light_skin_tone" skin_tone"
   ":person_bouncing_ball_medium_dark_skin_tone" medium_dark_skin_tone"
   ":person_bouncing_ball_medium_light_skin_tone" _medium_light_skin_tone"
   ":person_bouncing_ball_medium_skin_tone" skin_tone"
   ":person_bowing" 
   ":person_bowing_dark_skin_tone" 
   ":person_bowing_light_skin_tone" 
   ":person_bowing_medium_dark_skin_tone" skin_tone"
   ":person_bowing_medium_light_skin_tone" skin_tone"
   ":person_bowing_medium_skin_tone" 
   ":person_cartwheeling" 
   ":person_cartwheeling_dark_skin_tone" 
   ":person_cartwheeling_light_skin_tone" tone"
   ":person_cartwheeling_medium_dark_skin_tone" medium_dark_skin_tone"
   ":person_cartwheeling_medium_light_skin_tone" medium_light_skin_tone"
   ":person_cartwheeling_medium_skin_tone" tone"
   ":person_facepalming" 
   ":person_facepalming_dark_skin_tone" 
   ":person_facepalming_light_skin_tone" 
   ":person_facepalming_medium_dark_skin_tone" dark_skin_tone"
   ":person_facepalming_medium_light_skin_tone" medium_light_skin_tone"
   ":person_facepalming_medium_skin_tone" tone"
   ":person_fencing" 
   ":person_frowning" 
   ":person_frowning_dark_skin_tone" 
   ":person_frowning_light_skin_tone" 
   ":person_frowning_medium_dark_skin_tone" skin_tone"
   ":person_frowning_medium_light_skin_tone" skin_tone"
   ":person_frowning_medium_skin_tone" 
   ":person_gesturing_no" 
   ":person_gesturing_no_dark_skin_tone" 
   ":person_gesturing_no_light_skin_tone" skin_tone"
   ":person_gesturing_no_medium_dark_skin_tone" medium_dark_skin_tone"
   ":person_gesturing_no_medium_light_skin_tone" medium_light_skin_tone"
   ":person_gesturing_no_medium_skin_tone" skin_tone"
   ":person_gesturing_ok" 
   ":person_gesturing_ok_dark_skin_tone" 
   ":person_gesturing_ok_light_skin_tone" skin_tone"
   ":person_gesturing_ok_medium_dark_skin_tone" medium_dark_skin_tone"
   ":person_gesturing_ok_medium_light_skin_tone" medium_light_skin_tone"
   ":person_gesturing_ok_medium_skin_tone" skin_tone"
   ":person_getting_haircut" 
   ":person_getting_haircut_dark_skin_tone" skin_tone"
   ":person_getting_haircut_light_skin_tone" skin_tone"
   ":person_getting_haircut_medium_dark_skin_tone" haircut_medium_dark_skin_tone"
   ":person_getting_haircut_medium_light_skin_tone" haircut_medium_light_skin_tone"
   ":person_getting_haircut_medium_skin_tone" medium_skin_tone"
   ":person_getting_massage" 
   ":person_getting_massage_dark_skin_tone" skin_tone"
   ":person_getting_massage_light_skin_tone" skin_tone"
   ":person_getting_massage_medium_dark_skin_tone" massage_medium_dark_skin_tone"
   ":person_getting_massage_medium_light_skin_tone" massage_medium_light_skin_tone"
   ":person_getting_massage_medium_skin_tone" medium_skin_tone"
   ":person_golfing" 
   ":person_golfing_dark_skin_tone" 
   ":person_golfing_light_skin_tone" 
   ":person_golfing_medium_dark_skin_tone" skin_tone"
   ":person_golfing_medium_light_skin_tone" skin_tone"
   ":person_golfing_medium_skin_tone" 
   ":person_in_bed" 
   ":person_juggling" 
   ":person_juggling_dark_skin_tone" 
   ":person_juggling_light_skin_tone" 
   ":person_juggling_medium_dark_skin_tone" skin_tone"
   ":person_juggling_medium_light_skin_tone" skin_tone"
   ":person_juggling_medium_skin_tone" 
   ":person_lifting_weights" 
   ":person_lifting_weights_dark_skin_tone" skin_tone"
   ":person_lifting_weights_light_skin_tone" skin_tone"
   ":person_lifting_weights_medium_dark_skin_tone" weights_medium_dark_skin_tone"
   ":person_lifting_weights_medium_light_skin_tone" weights_medium_light_skin_tone"
   ":person_lifting_weights_medium_skin_tone" medium_skin_tone"
   ":person_mountain_biking" 
   ":person_mountain_biking_dark_skin_tone" skin_tone"
   ":person_mountain_biking_light_skin_tone" skin_tone"
   ":person_mountain_biking_medium_dark_skin_tone" biking_medium_dark_skin_tone"
   ":person_mountain_biking_medium_light_skin_tone" biking_medium_light_skin_tone"
   ":person_mountain_biking_medium_skin_tone" medium_skin_tone"
   ":person_playing_handball" 
   ":person_playing_handball_dark_skin_tone" skin_tone"
   ":person_playing_handball_light_skin_tone" light_skin_tone"
   ":person_playing_handball_medium_dark_skin_tone" handball_medium_dark_skin_tone"
   ":person_playing_handball_medium_light_skin_tone" _handball_medium_light_skin_tone"
   ":person_playing_handball_medium_skin_tone" medium_skin_tone"
   ":person_playing_water_polo" 
   ":person_playing_water_polo_dark_skin_tone" dark_skin_tone"
   ":person_playing_water_polo_light_skin_tone" polo_light_skin_tone"
   ":person_playing_water_polo_medium_dark_skin_tone" playing_water_polo_medium_dark_skin_tone"
   ":person_playing_water_polo_medium_light_skin_tone" playing_water_polo_medium_light_skin_tone"
   ":person_playing_water_polo_medium_skin_tone" polo_medium_skin_tone"
   ":person_pouting" 
   ":person_pouting_dark_skin_tone" 
   ":person_pouting_light_skin_tone" 
   ":person_pouting_medium_dark_skin_tone" skin_tone"
   ":person_pouting_medium_light_skin_tone" skin_tone"
   ":person_pouting_medium_skin_tone" 
   ":person_raising_hand" 
   ":person_raising_hand_dark_skin_tone" 
   ":person_raising_hand_light_skin_tone" skin_tone"
   ":person_raising_hand_medium_dark_skin_tone" medium_dark_skin_tone"
   ":person_raising_hand_medium_light_skin_tone" medium_light_skin_tone"
   ":person_raising_hand_medium_skin_tone" skin_tone"
   ":person_rowing_boat" 
   ":person_rowing_boat_dark_skin_tone" 
   ":person_rowing_boat_light_skin_tone" 
   ":person_rowing_boat_medium_dark_skin_tone" dark_skin_tone"
   ":person_rowing_boat_medium_light_skin_tone" medium_light_skin_tone"
   ":person_rowing_boat_medium_skin_tone" skin_tone"
   ":person_running" 
   ":person_running_dark_skin_tone" 
   ":person_running_light_skin_tone" 
   ":person_running_medium_dark_skin_tone" skin_tone"
   ":person_running_medium_light_skin_tone" skin_tone"
   ":person_running_medium_skin_tone" 
   ":person_shrugging" 
   ":person_shrugging_dark_skin_tone" 
   ":person_shrugging_light_skin_tone" 
   ":person_shrugging_medium_dark_skin_tone" skin_tone"
   ":person_shrugging_medium_light_skin_tone" light_skin_tone"
   ":person_shrugging_medium_skin_tone" 
   ":person_surfing" 
   ":person_surfing_dark_skin_tone" 
   ":person_surfing_light_skin_tone" 
   ":person_surfing_medium_dark_skin_tone" skin_tone"
   ":person_surfing_medium_light_skin_tone" skin_tone"
   ":person_surfing_medium_skin_tone" 
   ":person_swimming" 
   ":person_swimming_dark_skin_tone" 
   ":person_swimming_light_skin_tone" 
   ":person_swimming_medium_dark_skin_tone" skin_tone"
   ":person_swimming_medium_light_skin_tone" skin_tone"
   ":person_swimming_medium_skin_tone" 
   ":person_taking_bath" 
   ":person_taking_bath_dark_skin_tone" 
   ":person_taking_bath_light_skin_tone" 
   ":person_taking_bath_medium_dark_skin_tone" dark_skin_tone"
   ":person_taking_bath_medium_light_skin_tone" medium_light_skin_tone"
   ":person_taking_bath_medium_skin_tone" skin_tone"
   ":person_tipping_hand" 
   ":person_tipping_hand_dark_skin_tone" 
   ":person_tipping_hand_light_skin_tone" skin_tone"
   ":person_tipping_hand_medium_dark_skin_tone" medium_dark_skin_tone"
   ":person_tipping_hand_medium_light_skin_tone" medium_light_skin_tone"
   ":person_tipping_hand_medium_skin_tone" skin_tone"
   ":person_walking" 
   ":person_walking_dark_skin_tone" 
   ":person_walking_light_skin_tone" 
   ":person_walking_medium_dark_skin_tone" skin_tone"
   ":person_walking_medium_light_skin_tone" skin_tone"
   ":person_walking_medium_skin_tone" 
   ":person_wearing_turban" 
   ":person_wearing_turban_dark_skin_tone" skin_tone"
   ":person_wearing_turban_light_skin_tone" skin_tone"
   ":person_wearing_turban_medium_dark_skin_tone" turban_medium_dark_skin_tone"
   ":person_wearing_turban_medium_light_skin_tone" turban_medium_light_skin_tone"
   ":person_wearing_turban_medium_skin_tone" skin_tone"
   ":peru" 
   ":philippines" 
   ":pick" 
   ":pig" 
   ":pig_face" 
   ":pig_nose" 
   ":pile_of_poo" 
   ":pill" 
   ":pine_decoration" 
   ":pineapple" 
   ":ping_pong" 
   ":pisces" 
   ":pistol" 
   ":pitcairn_islands" 
   ":pizza" 
   ":place_of_worship" 
   ":play_button" 
   ":play_or_pause_button" 
   ":poland" 
   ":police_car" 
   ":police_car_light" 
   ":police_officer" 
   ":police_officer_dark_skin_tone" 
   ":police_officer_light_skin_tone" 
   ":police_officer_medium_dark_skin_tone" skin_tone"
   ":police_officer_medium_light_skin_tone" skin_tone"
   ":police_officer_medium_skin_tone" 
   ":poodle" 
   ":pool_8_ball" 
   ":popcorn" 
   ":portugal" 
   ":post_office" 
   ":postal_horn" 
   ":postbox" 
   ":pot_of_food" 
   ":potable_water" 
   ":potato" 
   ":poultry_leg" 
   ":pound_banknote" 
   ":pouting_cat_face" 
   ":pouting_face" 
   ":prayer_beads" 
   ":pregnant_woman" 
   ":pregnant_woman_dark_skin_tone" 
   ":pregnant_woman_light_skin_tone" 
   ":pregnant_woman_medium_dark_skin_tone" skin_tone"
   ":pregnant_woman_medium_light_skin_tone" skin_tone"
   ":pregnant_woman_medium_skin_tone" 
   ":prince" 
   ":prince_dark_skin_tone" 
   ":prince_light_skin_tone" 
   ":prince_medium_dark_skin_tone" 
   ":prince_medium_light_skin_tone" 
   ":prince_medium_skin_tone" 
   ":princess" 
   ":princess_dark_skin_tone" 
   ":princess_light_skin_tone" 
   ":princess_medium_dark_skin_tone" 
   ":princess_medium_light_skin_tone" 
   ":princess_medium_skin_tone" 
   ":printer" 
   ":prohibited" 
   ":puerto_rico" 
   ":purple_heart" 
   ":purse" 
   ":pushpin" 
   ":qatar" 
   ":question_mark" 
   ":rabbit" 
   ":rabbit_face" 
   ":racing_car" 
   ":radio" 
   ":radio_button" 
   ":radioactive" 
   ":railway_car" 
   ":railway_track" 
   ":rainbow" 
   ":rainbow_flag" 
   ":raised_back_of_hand" 
   ":raised_back_of_hand_dark_skin_tone" 
   ":raised_back_of_hand_light_skin_tone" tone"
   ":raised_back_of_hand_medium_dark_skin_tone" medium_dark_skin_tone"
   ":raised_back_of_hand_medium_light_skin_tone" medium_light_skin_tone"
   ":raised_back_of_hand_medium_skin_tone" tone"
   ":raised_fist" 
   ":raised_fist_dark_skin_tone" 
   ":raised_fist_light_skin_tone" 
   ":raised_fist_medium_dark_skin_tone" 
   ":raised_fist_medium_light_skin_tone" 
   ":raised_fist_medium_skin_tone" 
   ":raised_hand" 
   ":raised_hand_dark_skin_tone" 
   ":raised_hand_light_skin_tone" 
   ":raised_hand_medium_dark_skin_tone" 
   ":raised_hand_medium_light_skin_tone" 
   ":raised_hand_medium_skin_tone" 
   ":raising_hands" 
   ":raising_hands_dark_skin_tone" 
   ":raising_hands_light_skin_tone" 
   ":raising_hands_medium_dark_skin_tone" skin_tone"
   ":raising_hands_medium_light_skin_tone" skin_tone"
   ":raising_hands_medium_skin_tone" 
   ":ram" 
   ":rat" 
   ":record_button" 
   ":recycling_symbol" 
   ":red_apple" 
   ":red_circle" 
   ":red_heart" 
   ":red_paper_lantern" 
   ":red_triangle_pointed_down" 
   ":red_triangle_pointed_up" 
   ":registered" 
   ":relieved_face" 
   ":reminder_ribbon" 
   ":repeat_button" 
   ":repeat_single_button" 
   ":rescue_worker’s_helmet" 
   ":restroom" 
   ":reverse_button" 
   ":revolving_hearts" 
   ":réunion" 
   ":rhinoceros" 
   ":ribbon" 
   ":rice_ball" 
   ":rice_cracker" 
   ":right_anger_bubble" 
   ":right_arrow" 
   ":right_arrow_curving_down" 
   ":right_arrow_curving_left" 
   ":right_arrow_curving_up" 
   ":right_facing_fist" 
   ":right_facing_fist_dark_skin_tone" 
   ":right_facing_fist_light_skin_tone" 
   ":right_facing_fist_medium_dark_skin_tone" dark_skin_tone"
   ":right_facing_fist_medium_light_skin_tone" light_skin_tone"
   ":right_facing_fist_medium_skin_tone" 
   ":ring" 
   ":roasted_sweet_potato" 
   ":robot_face" 
   ":rocket" 
   ":rolled_up_newspaper" 
   ":roller_coaster" 
   ":rolling_on_the_floor_laughing" 
   ":romania" 
   ":rooster" 
   ":rose" 
   ":rosette" 
   ":round_pushpin" 
   ":rugby_football" 
   ":running_shirt" 
   ":running_shoe" 
   ":russia" 
   ":rwanda" 
   ":sad_but_relieved_face" 
   ":sagittarius" 
   ":sailboat" 
   ":sake" 
   ":samoa" 
   ":san_marino" 
   ":santa_claus" 
   ":santa_claus_dark_skin_tone" 
   ":santa_claus_light_skin_tone" 
   ":santa_claus_medium_dark_skin_tone" 
   ":santa_claus_medium_light_skin_tone" 
   ":santa_claus_medium_skin_tone" 
   ":satellite" 
   ":satellite_antenna" 
   ":saudi_arabia" 
   ":saxophone" 
   ":são_tomé__príncipe" 
   ":school" 
   ":school_backpack" 
   ":scissors" 
   ":scorpion" 
   ":scorpius" 
   ":scroll" 
   ":seat" 
   ":see_no_evil_monkey" 
   ":seedling" 
   ":selfie" 
   ":selfie_dark_skin_tone" 
   ":selfie_light_skin_tone" 
   ":selfie_medium_dark_skin_tone" 
   ":selfie_medium_light_skin_tone" 
   ":selfie_medium_skin_tone" 
   ":senegal" 
   ":serbia" 
   ":seven_o’clock" 
   ":seven_thirty" 
   ":seychelles" 
   ":shallow_pan_of_food" 
   ":shamrock" 
   ":shark" 
   ":shaved_ice" 
   ":sheaf_of_rice" 
   ":shield" 
   ":shinto_shrine" 
   ":ship" 
   ":shooting_star" 
   ":shopping_bags" 
   ":shopping_cart" 
   ":shortcake" 
   ":shower" 
   ":shrimp" 
   ":shuffle_tracks_button" 
   ":sierra_leone" 
   ":sign_of_the_horns" 
   ":sign_of_the_horns_dark_skin_tone" 
   ":sign_of_the_horns_light_skin_tone" 
   ":sign_of_the_horns_medium_dark_skin_tone" dark_skin_tone"
   ":sign_of_the_horns_medium_light_skin_tone" light_skin_tone"
   ":sign_of_the_horns_medium_skin_tone" 
   ":singapore" 
   ":sint_maarten" 
   ":six_o’clock" 
   ":six_thirty" 
   ":skier" 
   ":skis" 
   ":skull" 
   ":skull_and_crossbones" 
   ":sleeping_face" 
   ":sleepy_face" 
   ":slightly_frowning_face" 
   ":slightly_smiling_face" 
   ":slot_machine" 
   ":slovakia" 
   ":slovenia" 
   ":small_airplane" 
   ":small_blue_diamond" 
   ":small_orange_diamond" 
   ":smiling_cat_face_with_heart_eyes" 
   ":smiling_face" 
   ":smiling_face_with_halo" 
   ":smiling_face_with_heart_eyes" 
   ":smiling_face_with_horns" 
   ":smiling_face_with_smiling_eyes" 
   ":smiling_face_with_sunglasses" 
   ":smirking_face" 
   ":snail" 
   ":snake" 
   ":sneezing_face" 
   ":snow_capped_mountain" 
   ":snowboarder" 
   ":snowflake" 
   ":snowman" 
   ":snowman_without_snow" 
   ":soccer_ball" 
   ":soft_ice_cream" 
   ":solomon_islands" 
   ":somalia" 
   ":soon_arrow" 
   ":sos_button" 
   ":south_africa" 
   ":south_georgia__south_sandwich_islands" islands"
   ":south_korea" 
   ":south_sudan" 
   ":spade_suit" 
   ":spaghetti" 
   ":spain" 
   ":sparkle" 
   ":sparkler" 
   ":sparkles" 
   ":sparkling_heart" 
   ":speak_no_evil_monkey" 
   ":speaker_high_volume" 
   ":speaker_low_volume" 
   ":speaker_medium_volume" 
   ":speaking_head" 
   ":speech_balloon" 
   ":speedboat" 
   ":spider" 
   ":spider_web" 
   ":spiral_calendar" 
   ":spiral_notepad" 
   ":spiral_shell" 
   ":spoon" 
   ":sport_utility_vehicle" 
   ":sports_medal" 
   ":spouting_whale" 
   ":squid" 
   ":squinting_face_with_tongue" 
   ":sri_lanka" 
   ":st_barthélemy" 
   ":st_helena" 
   ":st_kitts__nevis" 
   ":st_lucia" 
   ":st_martin" 
   ":st_pierre__miquelon" 
   ":st_vincent__grenadines" 
   ":stadium" 
   ":star_and_crescent" 
   ":star_of_david" 
   ":station" 
   ":statue_of_liberty" 
   ":steaming_bowl" 
   ":stop_button" 
   ":stop_sign" 
   ":stopwatch" 
   ":straight_ruler" 
   ":strawberry" 
   ":studio_microphone" 
   ":stuffed_flatbread" 
   ":sudan" 
   ":sun" 
   ":sun_behind_cloud" 
   ":sun_behind_large_cloud" 
   ":sun_behind_rain_cloud" 
   ":sun_behind_small_cloud" 
   ":sun_with_face" 
   ":sunflower" 
   ":sunglasses" 
   ":sunrise" 
   ":sunrise_over_mountains" 
   ":sunset" 
   ":suriname" 
   ":sushi" 
   ":suspension_railway" 
   ":svalbard__jan_mayen" 
   ":swaziland" 
   ":sweat_droplets" 
   ":sweden" 
   ":switzerland" 
   ":synagogue" 
   ":syria" 
   ":syringe" 
   ":t_shirt" 
   ":taco" 
   ":taiwan" 
   ":tajikistan" 
   ":tanabata_tree" 
   ":tangerine" 
   ":tanzania" 
   ":taurus" 
   ":taxi" 
   ":teacup_without_handle" 
   ":tear_off_calendar" 
   ":telephone" 
   ":telephone_receiver" 
   ":telescope" 
   ":television" 
   ":ten_o’clock" 
   ":ten_thirty" 
   ":tennis" 
   ":tent" 
   ":thailand" 
   ":thermometer" 
   ":thinking_face" 
   ":thought_balloon" 
   ":three_o’clock" 
   ":three_thirty" 
   ":thumbs_down" 
   ":thumbs_down_dark_skin_tone" 
   ":thumbs_down_light_skin_tone" 
   ":thumbs_down_medium_dark_skin_tone" 
   ":thumbs_down_medium_light_skin_tone" 
   ":thumbs_down_medium_skin_tone" 
   ":thumbs_up" 
   ":thumbs_up_dark_skin_tone" 
   ":thumbs_up_light_skin_tone" 
   ":thumbs_up_medium_dark_skin_tone" 
   ":thumbs_up_medium_light_skin_tone" 
   ":thumbs_up_medium_skin_tone" 
   ":ticket" 
   ":tiger" 
   ":tiger_face" 
   ":timer_clock" 
   ":timor_leste" 
   ":tired_face" 
   ":togo" 
   ":toilet" 
   ":tokelau" 
   ":tokyo_tower" 
   ":tomato" 
   ":tonga" 
   ":tongue" 
   ":top_arrow" 
   ":top_hat" 
   ":tornado" 
   ":trackball" 
   ":tractor" 
   ":trade_mark" 
   ":train" 
   ":tram" 
   ":tram_car" 
   ":triangular_flag" 
   ":triangular_ruler" 
   ":trident_emblem" 
   ":trinidad__tobago" 
   ":tristan_da_cunha" 
   ":trolleybus" 
   ":trophy" 
   ":tropical_drink" 
   ":tropical_fish" 
   ":trumpet" 
   ":tulip" 
   ":tumbler_glass" 
   ":tunisia" 
   ":turkey" 
   ":turkmenistan" 
   ":turks__caicos_islands" 
   ":turtle" 
   ":tuvalu" 
   ":twelve_o’clock" 
   ":twelve_thirty" 
   ":two_hearts" 
   ":two_hump_camel" 
   ":two_men_holding_hands" 
   ":two_o’clock" 
   ":two_thirty" 
   ":two_women_holding_hands" 
   ":uganda" 
   ":ukraine" 
   ":umbrella" 
   ":umbrella_on_ground" 
   ":umbrella_with_rain_drops" 
   ":unamused_face" 
   ":unicorn_face" 
   ":united_arab_emirates" 
   ":united_kingdom" 
   ":united_states" 
   ":unlocked" 
   ":up_arrow" 
   ":up_button" 
   ":up_down_arrow" 
   ":up_left_arrow" 
   ":up_right_arrow" 
   ":upside_down_face" 
   ":uruguay" 
   ":us_outlying_islands" 
   ":us_virgin_islands" 
   ":uzbekistan" 
   ":vanuatu" 
   ":vatican_city" 
   ":venezuela" 
   ":vertical_traffic_light" 
   ":vibration_mode" 
   ":victory_hand" 
   ":victory_hand_dark_skin_tone" 
   ":victory_hand_light_skin_tone" 
   ":victory_hand_medium_dark_skin_tone" 
   ":victory_hand_medium_light_skin_tone" skin_tone"
   ":victory_hand_medium_skin_tone" 
   ":video_camera" 
   ":video_game" 
   ":videocassette" 
   ":vietnam" 
   ":violin" 
   ":virgo" 
   ":volcano" 
   ":volleyball" 
   ":vs_button" 
   ":vulcan_salute" 
   ":vulcan_salute_dark_skin_tone" 
   ":vulcan_salute_light_skin_tone" 
   ":vulcan_salute_medium_dark_skin_tone" skin_tone"
   ":vulcan_salute_medium_light_skin_tone" skin_tone"
   ":vulcan_salute_medium_skin_tone" 
   ":wallis__futuna" 
   ":waning_crescent_moon" 
   ":waning_gibbous_moon" 
   ":warning" 
   ":wastebasket" 
   ":watch" 
   ":water_buffalo" 
   ":water_closet" 
   ":water_wave" 
   ":watermelon" 
   ":waving_hand" 
   ":waving_hand_dark_skin_tone" 
   ":waving_hand_light_skin_tone" 
   ":waving_hand_medium_dark_skin_tone" 
   ":waving_hand_medium_light_skin_tone" 
   ":waving_hand_medium_skin_tone" 
   ":wavy_dash" 
   ":waxing_crescent_moon" 
   ":waxing_gibbous_moon" 
   ":weary_cat_face" 
   ":weary_face" 
   ":wedding" 
   ":western_sahara" 
   ":whale" 
   ":wheel_of_dharma" 
   ":wheelchair_symbol" 
   ":white_circle" 
   ":white_exclamation_mark" 
   ":white_flag" 
   ":white_flower" 
   ":white_heavy_check_mark" 
   ":white_large_square" 
   ":white_medium_small_square" 
   ":white_medium_square" 
   ":white_medium_star" 
   ":white_question_mark" 
   ":white_small_square" 
   ":white_square_button" 
   ":wilted_flower" 
   ":wind_chime" 
   ":wind_face" 
   ":wine_glass" 
   ":winking_face" 
   ":winking_face_with_tongue" 
   ":wolf_face" 
   ":woman" 
   ":woman_artist" 
   ":woman_artist_dark_skin_tone" 
   ":woman_artist_light_skin_tone" 
   ":woman_artist_medium_dark_skin_tone" 
   ":woman_artist_medium_light_skin_tone" skin_tone"
   ":woman_artist_medium_skin_tone" 
   ":woman_astronaut" 
   ":woman_astronaut_dark_skin_tone" 
   ":woman_astronaut_light_skin_tone" 
   ":woman_astronaut_medium_dark_skin_tone" skin_tone"
   ":woman_astronaut_medium_light_skin_tone" skin_tone"
   ":woman_astronaut_medium_skin_tone" 
   ":woman_biking" 
   ":woman_biking_dark_skin_tone" 
   ":woman_biking_light_skin_tone" 
   ":woman_biking_medium_dark_skin_tone" 
   ":woman_biking_medium_light_skin_tone" skin_tone"
   ":woman_biking_medium_skin_tone" 
   ":woman_bouncing_ball" 
   ":woman_bouncing_ball_dark_skin_tone" 
   ":woman_bouncing_ball_light_skin_tone" skin_tone"
   ":woman_bouncing_ball_medium_dark_skin_tone" medium_dark_skin_tone"
   ":woman_bouncing_ball_medium_light_skin_tone" medium_light_skin_tone"
   ":woman_bouncing_ball_medium_skin_tone" skin_tone"
   ":woman_bowing" 
   ":woman_bowing_dark_skin_tone" 
   ":woman_bowing_light_skin_tone" 
   ":woman_bowing_medium_dark_skin_tone" 
   ":woman_bowing_medium_light_skin_tone" skin_tone"
   ":woman_bowing_medium_skin_tone" 
   ":woman_cartwheeling" 
   ":woman_cartwheeling_dark_skin_tone" 
   ":woman_cartwheeling_light_skin_tone" 
   ":woman_cartwheeling_medium_dark_skin_tone" dark_skin_tone"
   ":woman_cartwheeling_medium_light_skin_tone" medium_light_skin_tone"
   ":woman_cartwheeling_medium_skin_tone" tone"
   ":woman_construction_worker" 
   ":woman_construction_worker_dark_skin_tone" dark_skin_tone"
   ":woman_construction_worker_light_skin_tone" worker_light_skin_tone"
   ":woman_construction_worker_medium_dark_skin_tone" construction_worker_medium_dark_skin_tone"
   ":woman_construction_worker_medium_light_skin_tone" construction_worker_medium_light_skin_tone"
   ":woman_construction_worker_medium_skin_tone" worker_medium_skin_tone"
   ":woman_cook" 
   ":woman_cook_dark_skin_tone" 
   ":woman_cook_light_skin_tone" 
   ":woman_cook_medium_dark_skin_tone" 
   ":woman_cook_medium_light_skin_tone" 
   ":woman_cook_medium_skin_tone" 
   ":woman_dancing" 
   ":woman_dancing_dark_skin_tone" 
   ":woman_dancing_light_skin_tone" 
   ":woman_dancing_medium_dark_skin_tone" skin_tone"
   ":woman_dancing_medium_light_skin_tone" skin_tone"
   ":woman_dancing_medium_skin_tone" 
   ":woman_dark_skin_tone" 
   ":woman_detective" 
   ":woman_detective_dark_skin_tone" 
   ":woman_detective_light_skin_tone" 
   ":woman_detective_medium_dark_skin_tone" skin_tone"
   ":woman_detective_medium_light_skin_tone" skin_tone"
   ":woman_detective_medium_skin_tone" 
   ":woman_facepalming" 
   ":woman_facepalming_dark_skin_tone" 
   ":woman_facepalming_light_skin_tone" 
   ":woman_facepalming_medium_dark_skin_tone" dark_skin_tone"
   ":woman_facepalming_medium_light_skin_tone" light_skin_tone"
   ":woman_facepalming_medium_skin_tone" 
   ":woman_factory_worker" 
   ":woman_factory_worker_dark_skin_tone" skin_tone"
   ":woman_factory_worker_light_skin_tone" skin_tone"
   ":woman_factory_worker_medium_dark_skin_tone" medium_dark_skin_tone"
   ":woman_factory_worker_medium_light_skin_tone" _medium_light_skin_tone"
   ":woman_factory_worker_medium_skin_tone" skin_tone"
   ":woman_farmer" 
   ":woman_farmer_dark_skin_tone" 
   ":woman_farmer_light_skin_tone" 
   ":woman_farmer_medium_dark_skin_tone" 
   ":woman_farmer_medium_light_skin_tone" skin_tone"
   ":woman_farmer_medium_skin_tone" 
   ":woman_firefighter" 
   ":woman_firefighter_dark_skin_tone" 
   ":woman_firefighter_light_skin_tone" 
   ":woman_firefighter_medium_dark_skin_tone" dark_skin_tone"
   ":woman_firefighter_medium_light_skin_tone" light_skin_tone"
   ":woman_firefighter_medium_skin_tone" 
   ":woman_frowning" 
   ":woman_frowning_dark_skin_tone" 
   ":woman_frowning_light_skin_tone" 
   ":woman_frowning_medium_dark_skin_tone" skin_tone"
   ":woman_frowning_medium_light_skin_tone" skin_tone"
   ":woman_frowning_medium_skin_tone" 
   ":woman_gesturing_no" 
   ":woman_gesturing_no_dark_skin_tone" 
   ":woman_gesturing_no_light_skin_tone" 
   ":woman_gesturing_no_medium_dark_skin_tone" dark_skin_tone"
   ":woman_gesturing_no_medium_light_skin_tone" medium_light_skin_tone"
   ":woman_gesturing_no_medium_skin_tone" skin_tone"
   ":woman_gesturing_ok" 
   ":woman_gesturing_ok_dark_skin_tone" 
   ":woman_gesturing_ok_light_skin_tone" 
   ":woman_gesturing_ok_medium_dark_skin_tone" dark_skin_tone"
   ":woman_gesturing_ok_medium_light_skin_tone" medium_light_skin_tone"
   ":woman_gesturing_ok_medium_skin_tone" skin_tone"
   ":woman_getting_haircut" 
   ":woman_getting_haircut_dark_skin_tone" skin_tone"
   ":woman_getting_haircut_light_skin_tone" skin_tone"
   ":woman_getting_haircut_medium_dark_skin_tone" haircut_medium_dark_skin_tone"
   ":woman_getting_haircut_medium_light_skin_tone" haircut_medium_light_skin_tone"
   ":woman_getting_haircut_medium_skin_tone" skin_tone"
   ":woman_getting_massage" 
   ":woman_getting_massage_dark_skin_tone" skin_tone"
   ":woman_getting_massage_light_skin_tone" skin_tone"
   ":woman_getting_massage_medium_dark_skin_tone" massage_medium_dark_skin_tone"
   ":woman_getting_massage_medium_light_skin_tone" massage_medium_light_skin_tone"
   ":woman_getting_massage_medium_skin_tone" skin_tone"
   ":woman_golfing" 
   ":woman_golfing_dark_skin_tone" 
   ":woman_golfing_light_skin_tone" 
   ":woman_golfing_medium_dark_skin_tone" skin_tone"
   ":woman_golfing_medium_light_skin_tone" skin_tone"
   ":woman_golfing_medium_skin_tone" 
   ":woman_guard" 
   ":woman_guard_dark_skin_tone" 
   ":woman_guard_light_skin_tone" 
   ":woman_guard_medium_dark_skin_tone" 
   ":woman_guard_medium_light_skin_tone" 
   ":woman_guard_medium_skin_tone" 
   ":woman_health_worker" 
   ":woman_health_worker_dark_skin_tone" 
   ":woman_health_worker_light_skin_tone" skin_tone"
   ":woman_health_worker_medium_dark_skin_tone" medium_dark_skin_tone"
   ":woman_health_worker_medium_light_skin_tone" medium_light_skin_tone"
   ":woman_health_worker_medium_skin_tone" skin_tone"
   ":woman_judge" 
   ":woman_judge_dark_skin_tone" 
   ":woman_judge_light_skin_tone" 
   ":woman_judge_medium_dark_skin_tone" 
   ":woman_judge_medium_light_skin_tone" 
   ":woman_judge_medium_skin_tone" 
   ":woman_juggling" 
   ":woman_juggling_dark_skin_tone" 
   ":woman_juggling_light_skin_tone" 
   ":woman_juggling_medium_dark_skin_tone" skin_tone"
   ":woman_juggling_medium_light_skin_tone" skin_tone"
   ":woman_juggling_medium_skin_tone" 
   ":woman_lifting_weights" 
   ":woman_lifting_weights_dark_skin_tone" skin_tone"
   ":woman_lifting_weights_light_skin_tone" skin_tone"
   ":woman_lifting_weights_medium_dark_skin_tone" weights_medium_dark_skin_tone"
   ":woman_lifting_weights_medium_light_skin_tone" weights_medium_light_skin_tone"
   ":woman_lifting_weights_medium_skin_tone" skin_tone"
   ":woman_light_skin_tone" 
   ":woman_mechanic" 
   ":woman_mechanic_dark_skin_tone" 
   ":woman_mechanic_light_skin_tone" 
   ":woman_mechanic_medium_dark_skin_tone" skin_tone"
   ":woman_mechanic_medium_light_skin_tone" skin_tone"
   ":woman_mechanic_medium_skin_tone" 
   ":woman_medium_dark_skin_tone" 
   ":woman_medium_light_skin_tone" 
   ":woman_medium_skin_tone" 
   ":woman_mountain_biking" 
   ":woman_mountain_biking_dark_skin_tone" skin_tone"
   ":woman_mountain_biking_light_skin_tone" skin_tone"
   ":woman_mountain_biking_medium_dark_skin_tone" biking_medium_dark_skin_tone"
   ":woman_mountain_biking_medium_light_skin_tone" biking_medium_light_skin_tone"
   ":woman_mountain_biking_medium_skin_tone" skin_tone"
   ":woman_office_worker" 
   ":woman_office_worker_dark_skin_tone" 
   ":woman_office_worker_light_skin_tone" skin_tone"
   ":woman_office_worker_medium_dark_skin_tone" medium_dark_skin_tone"
   ":woman_office_worker_medium_light_skin_tone" medium_light_skin_tone"
   ":woman_office_worker_medium_skin_tone" skin_tone"
   ":woman_pilot" 
   ":woman_pilot_dark_skin_tone" 
   ":woman_pilot_light_skin_tone" 
   ":woman_pilot_medium_dark_skin_tone" 
   ":woman_pilot_medium_light_skin_tone" 
   ":woman_pilot_medium_skin_tone" 
   ":woman_playing_handball" 
   ":woman_playing_handball_dark_skin_tone" skin_tone"
   ":woman_playing_handball_light_skin_tone" skin_tone"
   ":woman_playing_handball_medium_dark_skin_tone" handball_medium_dark_skin_tone"
   ":woman_playing_handball_medium_light_skin_tone" handball_medium_light_skin_tone"
   ":woman_playing_handball_medium_skin_tone" medium_skin_tone"
   ":woman_playing_water_polo" 
   ":woman_playing_water_polo_dark_skin_tone" dark_skin_tone"
   ":woman_playing_water_polo_light_skin_tone" light_skin_tone"
   ":woman_playing_water_polo_medium_dark_skin_tone" water_polo_medium_dark_skin_tone"
   ":woman_playing_water_polo_medium_light_skin_tone" playing_water_polo_medium_light_skin_tone"
   ":woman_playing_water_polo_medium_skin_tone" _medium_skin_tone"
   ":woman_police_officer" 
   ":woman_police_officer_dark_skin_tone" skin_tone"
   ":woman_police_officer_light_skin_tone" skin_tone"
   ":woman_police_officer_medium_dark_skin_tone" medium_dark_skin_tone"
   ":woman_police_officer_medium_light_skin_tone" _medium_light_skin_tone"
   ":woman_police_officer_medium_skin_tone" skin_tone"
   ":woman_pouting" 
   ":woman_pouting_dark_skin_tone" 
   ":woman_pouting_light_skin_tone" 
   ":woman_pouting_medium_dark_skin_tone" skin_tone"
   ":woman_pouting_medium_light_skin_tone" skin_tone"
   ":woman_pouting_medium_skin_tone" 
   ":woman_raising_hand" 
   ":woman_raising_hand_dark_skin_tone" 
   ":woman_raising_hand_light_skin_tone" 
   ":woman_raising_hand_medium_dark_skin_tone" dark_skin_tone"
   ":woman_raising_hand_medium_light_skin_tone" medium_light_skin_tone"
   ":woman_raising_hand_medium_skin_tone" skin_tone"
   ":woman_rowing_boat" 
   ":woman_rowing_boat_dark_skin_tone" 
   ":woman_rowing_boat_light_skin_tone" 
   ":woman_rowing_boat_medium_dark_skin_tone" dark_skin_tone"
   ":woman_rowing_boat_medium_light_skin_tone" light_skin_tone"
   ":woman_rowing_boat_medium_skin_tone" 
   ":woman_running" 
   ":woman_running_dark_skin_tone" 
   ":woman_running_light_skin_tone" 
   ":woman_running_medium_dark_skin_tone" skin_tone"
   ":woman_running_medium_light_skin_tone" skin_tone"
   ":woman_running_medium_skin_tone" 
   ":woman_scientist" 
   ":woman_scientist_dark_skin_tone" 
   ":woman_scientist_light_skin_tone" 
   ":woman_scientist_medium_dark_skin_tone" skin_tone"
   ":woman_scientist_medium_light_skin_tone" skin_tone"
   ":woman_scientist_medium_skin_tone" 
   ":woman_shrugging" 
   ":woman_shrugging_dark_skin_tone" 
   ":woman_shrugging_light_skin_tone" 
   ":woman_shrugging_medium_dark_skin_tone" skin_tone"
   ":woman_shrugging_medium_light_skin_tone" skin_tone"
   ":woman_shrugging_medium_skin_tone" 
   ":woman_singer" 
   ":woman_singer_dark_skin_tone" 
   ":woman_singer_light_skin_tone" 
   ":woman_singer_medium_dark_skin_tone" 
   ":woman_singer_medium_light_skin_tone" skin_tone"
   ":woman_singer_medium_skin_tone" 
   ":woman_student" 
   ":woman_student_dark_skin_tone" 
   ":woman_student_light_skin_tone" 
   ":woman_student_medium_dark_skin_tone" skin_tone"
   ":woman_student_medium_light_skin_tone" skin_tone"
   ":woman_student_medium_skin_tone" 
   ":woman_surfing" 
   ":woman_surfing_dark_skin_tone" 
   ":woman_surfing_light_skin_tone" 
   ":woman_surfing_medium_dark_skin_tone" skin_tone"
   ":woman_surfing_medium_light_skin_tone" skin_tone"
   ":woman_surfing_medium_skin_tone" 
   ":woman_swimming" 
   ":woman_swimming_dark_skin_tone" 
   ":woman_swimming_light_skin_tone" 
   ":woman_swimming_medium_dark_skin_tone" skin_tone"
   ":woman_swimming_medium_light_skin_tone" skin_tone"
   ":woman_swimming_medium_skin_tone" 
   ":woman_teacher" 
   ":woman_teacher_dark_skin_tone" 
   ":woman_teacher_light_skin_tone" 
   ":woman_teacher_medium_dark_skin_tone" skin_tone"
   ":woman_teacher_medium_light_skin_tone" skin_tone"
   ":woman_teacher_medium_skin_tone" 
   ":woman_technologist" 
   ":woman_technologist_dark_skin_tone" 
   ":woman_technologist_light_skin_tone" 
   ":woman_technologist_medium_dark_skin_tone" dark_skin_tone"
   ":woman_technologist_medium_light_skin_tone" medium_light_skin_tone"
   ":woman_technologist_medium_skin_tone" tone"
   ":woman_tipping_hand" 
   ":woman_tipping_hand_dark_skin_tone" 
   ":woman_tipping_hand_light_skin_tone" 
   ":woman_tipping_hand_medium_dark_skin_tone" dark_skin_tone"
   ":woman_tipping_hand_medium_light_skin_tone" medium_light_skin_tone"
   ":woman_tipping_hand_medium_skin_tone" skin_tone"
   ":woman_walking" 
   ":woman_walking_dark_skin_tone" 
   ":woman_walking_light_skin_tone" 
   ":woman_walking_medium_dark_skin_tone" skin_tone"
   ":woman_walking_medium_light_skin_tone" skin_tone"
   ":woman_walking_medium_skin_tone" 
   ":woman_wearing_turban" 
   ":woman_wearing_turban_dark_skin_tone" skin_tone"
   ":woman_wearing_turban_light_skin_tone" skin_tone"
   ":woman_wearing_turban_medium_dark_skin_tone" medium_dark_skin_tone"
   ":woman_wearing_turban_medium_light_skin_tone" _medium_light_skin_tone"
   ":woman_wearing_turban_medium_skin_tone" skin_tone"
   ":woman’s_boot" 
   ":woman’s_clothes" 
   ":woman’s_hat" 
   ":woman’s_sandal" 
   ":women_with_bunny_ears" 
   ":women_wrestling" 
   ":women’s_room" 
   ":world_map" 
   ":worried_face" 
   ":wrapped_gift" 
   ":wrench" 
   ":writing_hand" 
   ":writing_hand_dark_skin_tone" 
   ":writing_hand_light_skin_tone" 
   ":writing_hand_medium_dark_skin_tone" 
   ":writing_hand_medium_light_skin_tone" skin_tone"
   ":writing_hand_medium_skin_tone" 
   ":yellow_heart" 
   ":yemen" 
   ":yen_banknote" 
   ":yin_yang" 
   ":zambia" 
   ":zimbabwe" 
   ":zipper_mouth_face" 
   ":zzz" 
```
